export SRC=/Users/smaant/src
export GOPATH=$SRC/go
export PATH="/Users/smaant/bin:/opt/local/bin:/opt/local/sbin:/usr/local/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/X11R6/bin:$GOPATH/bin:~/Library/Haskell/bin"